name: "Pantheon deploy"
description: "This GitHub Action deploys your current issue branch to a remote Pantheon repo."
author: "irishdistillers"
inputs:
  ACTION:
    description: "action to run: create-multidev | delete-multidev | merge-to-dev"
    required: true
  BRANCH_NAME:
    description: "the branch you want to send to Pantheon"
    required: true
  PANTHEON_SITE_ID:
    description: "Pantheon site ID e.g: domain"
    required: true
  PANTHEON_REPO_URL:
    description: "Pantheon GIT Repo URL"
    required: true
  STRICT_BRANCH_NAME:
    description: "(optional) Set to `strict` if you want your branch names to only look like Jira tickets (ABC-1234)"
    default: "none"

outputs:
  multidev:
    description: "Info about the multidev"

runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "truck"
