name: "Pantheon deploy"
description: "This GitHub Action deploys your current issue branch to a remote Pantheon repo."
author: "irishdistillers"
inputs:
  PULL_REQUEST_STATE:
    description: "State of the PR that triggered the action (open/close/...)"
    required: true
  PANTHEON_SITE_ID:
    description: "Remote GIT Repo Name"
    required: true
  PANTHEON_REPO_URL:
    description: "Remote GIT Repo URL"
    required: true
  STRICT_BRANCH_NAMES:
    description: "(optional) Set to `strict` if you want your branch names to only look like Jira tickets (ABC-1234)"
    default: "none"
  
outputs:
  multidev:
    description: "Info about the multidev"

runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "truck"
