name: "Pantheon deploy"
description: "This GitHub Action deploys your current issue branch to a remote Pantheon repo."
author: "irishdistillers"
inputs:
  PANTHEON_MACHINE_TOKEN:
    description: "Pantheon Machine Token to be used in Terminus"
    required: true
  REMOTE_REPO_URL:
    description: "Remote GIT Repo URL"
    required: true
  REMOTE_REPO_NAME:
    description: "Remote GIT Repo Name"
    required: true
outputs:
  multidev-url:
    description: "URL to access the created multidev"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "truck"
